version: '2.1'

services:
  cscourseplanning:
    image: cscourseplanning
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 4000:4000
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules